name = "julia_repo_setup"
uuid = "abaa0e88-a45f-4691-aa5a-4bc44c0aea8a"
authors = ["Norel <norel.evoagile@gmail.com> and contributors"]
version = "0.1.0-DEV"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Example = "7876af07-990d-54b4-ab0e-23690620f79a"

[compat]
Example = "0.5"
Documenter = "0.27"
julia = "1.8.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
